[chore] fix the links in project readme
oras-project/oras pull request #1012
Opened 2023-07-08 15:10 UTC by amands98

This PR fixes the links.

**Please check the following list**:
- [ ]  Does the affected code have corresponding tests, e.g. unit test, E2E test?
- [ ]  Does this change require a documentation update?
- [ ]  Does this introduce breaking changes that would require an announcement or bumping the major version?
- [ ]  Do all new files have an appropriate license header?

2023-07-09 12:52 UTC, TerryHowe requested changes

2023-07-09 12:52 UTC, TerryHowe commented on README.md
> +Refer to the [development guide](https://oras.land/docs/how_to_guides/developer_guide) to get started [contributing to ORAS](https://oras.land/docs/community/contributing_guide).
```suggestion
Refer to the [development guide](https://oras.land/docs/community/developer_guide) to get started [contributing to ORAS](https://oras.land/docs/community/contributing_guide).
```

2023-07-10 12:31 UTC, TerryHowe approved these changes
/lgtm

2023-07-11 14:32 UTC, qweeah commented
LGTM but @amands98 can you help rebase the PR to main branch, thanks.

2023-07-12 00:33 UTC, merged

2023-07-12 15:13 UTC, amands98 commented
First PR merged, more to come.