feat: improve error message when detecting conflicting flags
oras-project/oras pull request #1345
Opened 2024-04-15 07:47 UTC by wangxiaoxuan273

**What this PR does / why we need it**:
Improve error message when detecting conflicting flags. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1340 

**Please check the following list**:
- [ ]  Does the affected code have corresponding tests, e.g. unit test, E2E test?
- [ ]  Does this change require a documentation update?
- [ ]  Does this introduce breaking changes that would require an announcement or bumping the major version?
- [ ]  Do all new files have an appropriate license header?

2024-04-15 08:10 UTC, qweeah requested changes

2024-04-15 08:49 UTC, qweeah commented on cmd/oras/internal/option/remote.go
> +		if len(changedFlags) >= 2 {
Return all conflicted flags in a flag set with error like `--%s, --%s, --%s cannot be used at the same time`

2024-04-15 08:50 UTC, qweeah commented on cmd/oras/internal/option/remote.go
> +func CheckMutuallyExclusiveFlags(cmd *cobra.Command, exclusiveFlagSets ...[]string) error {
Add a comment on how the argument `...[]string` will be used, e.g. it detects the first set of conflict and returns the error without checking all the flag sets.

2024-04-16 03:20 UTC, qweeah commented on cmd/oras/internal/errors/errors.go
> +			flags := strings.Join(changedFlags, ", ")
need extra loop to add `--` as prefix to **ALL** the changed flag。

2024-04-16 03:22 UTC, qweeah commented on cmd/oras/internal/errors/errors.go
> +			return fmt.Errorf("--%s cannot be used at the same time", flags)
Do we still need `--`?
```suggestion
			return fmt.Errorf("%s cannot be used at the same time", flags)
```

2024-04-16 03:25 UTC, qweeah commented on cmd/oras/internal/errors/errors.go
> +			return fmt.Errorf("--%s cannot be used at the same time", flags)
```suggestion
			return fmt.Errorf("%s cannot be used at the same time", strings.Join(changedFlags, ", "))
```

2024-04-16 07:46 UTC, wangxiaoxuan273 commented on cmd/oras/internal/errors/errors.go
> +			return fmt.Errorf("--%s cannot be used at the same time", flags)
My mistake

2024-04-16 08:03 UTC, qweeah approved these changes
LGTM

2024-04-16 08:03 UTC, merged