refactor: Moave testutils to general location
oras-project/oras pull request #1459
Opened 2024-07-27 14:11 UTC by TerryHowe

**What this PR does / why we need it**:

The successor PR is big and still lacks coverage without more changes. This PR is for a small part of that change, just moving the console testutils to internal/testutils so we can have one testutils that is ignored by coverage.

2024-08-02 09:22 UTC, qweeah requested changes

2024-08-02 09:22 UTC, qweeah commented on internal/testutils/testutils.go
How about renaming this file to `console.go`?

2024-08-02 09:22 UTC, qweeah commented on Makefile
> +	$(GO_EXE) test -race -v -coverprofile=coverage-all.txt -covermode=atomic -coverpkg=./... ./...
How about modifying `-coverpkg`? Like

> $(GO_EXE) test -race -v -coverprofile=coverage-all.txt -covermode=atomic -coverpkg=$(go list ./... | grep -v internal/testutils | tr '\n' ',') ./...

2024-08-02 20:46 UTC, TerryHowe commented on internal/testutils/testutils.go
Done

2024-08-02 20:46 UTC, TerryHowe commented on Makefile
> +	$(GO_EXE) test -race -v -coverprofile=coverage-all.txt -covermode=atomic -coverpkg=./... ./...
Done.

2024-08-03 03:52 UTC, qweeah approved these changes
LGTM with minor suggestion.

2024-08-03 03:52 UTC, qweeah commented on .gitignore
> +coverage-all.txt
No need to ignore this file

2024-08-03 13:08 UTC, TerryHowe commented on .gitignore
> +coverage-all.txt
Done

2024-08-03 13:27 UTC, merged