refactor: create an interface for status console
oras-project/oras pull request #1481
Opened 2024-08-16 22:44 UTC by TerryHowe

**What this PR does / why we need it**:

Create a interface for console so that alternate implementations can exist. In doing this, I found the `Size()` method was not properly implemented, so I created a `GetHeightWidth()` method.

Partial: https://github.com/oras-project/oras/issues/1461

2024-09-26 10:49 UTC, sabre1041 approved these changes
LGTM

2024-09-28 20:25 UTC, sabre1041 approved these changes

2024-09-29 07:17 UTC, qweeah requested changes

2024-09-29 07:17 UTC, qweeah commented on cmd/oras/internal/display/status/console/console.go
>  }
Can we merge the implementation to those two functions? It's strange to make `Size` public but `console` is private.

2024-09-29 07:17 UTC, qweeah approved these changes
Thanks Terry for contributing. LGTM with minor sugggestions.

2024-09-29 07:18 UTC, qweeah approved these changes
LGTM with minor suggestions.

2024-09-30 01:37 UTC, qweeah approved these changes
LGTM

2024-09-30 01:38 UTC, merged