feature: build binary for OS and arch by default
oras-project/oras pull request #1487
Opened 2024-08-22 14:21 UTC by TerryHowe

**What this PR does / why we need it**:

Build the binary by default for the current OS and arch.

2024-09-05 13:59 UTC, qweeah requested changes

2024-09-05 13:59 UTC, qweeah commented on Makefile
> +default: test build-mac-$(ARCH)
Should it be
```suggestion
default: test build-$(OS)-$(ARCH)
```

2024-09-06 01:58 UTC, qweeah commented on Makefile
> +endif
extra line?
```suggestion
```

2024-09-09 15:40 UTC, TerryHowe commented on Makefile
> +endif
Thanks. Updated and my goal here is just to support amd64, arm64 on mac or Linux.

2024-09-12 06:49 UTC, qweeah approved these changes
LGTM. Validated on Ubuntu and MAC

2024-09-12 17:01 UTC, merged