Add OCI Conformance validation with ORAS
oras-project/oras pull request #257
Opened 2021-04-07 23:08 UTC by SteveLasker

Add several steps to validate if a registry supports OCI Artifact types using `oras push|pull` 

Signed-off-by: Steve Lasker <stevenlasker@hotmail.com>

2021-04-08 18:07 UTC, sajayantony requested changes

2021-04-08 18:07 UTC, sajayantony commented on docs/registry-conformance.md
> +  ./artifact.txt:application/txt
would you like to use recommended mime types like text/plain? 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types/Common_types

2021-04-08 18:47 UTC, jdolitsky requested changes
I think this is better to be codified. Perhaps a bash script that runs these commands, taking REGISTRY_URL REGISTRY_NAMESPACE REGISTRY_USERNAME REGISTRY_PASSWORD as env vars

2021-04-08 18:49 UTC, jdolitsky commented
Can also wrap this in robot framework to get some better output. See this example in Helm: https://github.com/helm/acceptance-testing/blob/main/testsuites/repos.robot

2021-04-09 18:09 UTC, SteveLasker commented
:eyes:
Thanks, folks. I'll get this incorporated next week.

2022-11-08 21:17 UTC, sajayantony commented
This was a good starting point for the discussions that lead OCI artifacts. Given that we now have - https://github.com/opencontainers/distribution-spec/tree/main/conformance and ORAS repo has all the E2E tests planned do we need this PR or can we close it @SteveLasker

2022-11-08 22:38 UTC, SteveLasker commented
This was initially created to help docker enable oci artifacts. Now that they’re done, every other registry now enables OcI Artifacts, and there’s better codified solution, happy to close this one.

2022-11-08 22:38 UTC, closed without merging