feat: export manifest descriptor by push
oras-project/oras pull request #524
Opened 2022-08-23 08:38 UTC by jasminetMSFT

resolves #497 
Signed-off-by: JasmineTang <jasminetang@microsoft.com>

2022-08-23 15:46 UTC, qweeah requested changes

2022-08-23 15:46 UTC, qweeah commented on cmd/oras/internal/option/packer.go
> +		Size:      desc.Size,
Can you confirm what is need in this descriptor? 

I saw in @shizhMSFT‘s [comment](https://github.com/oras-project/oras/issues/497#issuecomment-1216325804), the ` "containerimage.descriptor"` also contains annotation.

2022-08-23 15:46 UTC, qweeah commented on cmd/oras/push.go
>  	return opts.ExportManifest(ctx, store, desc)
Will both manifest content and descriptor be printed out both `--export-manifest-descriptor` and `--export-manifest` are specified?

2022-11-03 06:00 UTC, jasminetMSFT commented
This PR will be covered by [Oras commands like attach, discover, and pull support an option to format output as JSON · Issue #638 · oras-project/oras (github.com)](https://github.com/oras-project/oras/issues/638), so I will close this PR.

2022-11-03 06:00 UTC, closed without merging