fix: provide function to support hostname mapping
oras-project/oras pull request #549
Opened 2022-09-09 07:13 UTC by junczhu

Resolve: #542 
Signed-off-by: Juncheng Zhu <junczhu@microsoft.com>

2022-09-09 13:08 UTC, qweeah commented
What if username/password are passed through flags? Replacing host name in cred store only works when credential is empty,  see 
https://github.com/oras-project/oras/blob/main/cmd/oras/internal/option/remote.go#L152

2022-09-10 09:12 UTC, qweeah commented on internal/credential/store.go
> +func convertHostname(registry string) string {
use [registry.Host](https://github.com/oras-project/oras-go/blob/main/registry/reference.go#L177) directly

2022-09-10 09:38 UTC, shizhMSFT commented
@qweeah I've discussed offline with @junczhu. The behavior of `docker.io` in docker is special that it connects to the host of `registry-1.docker.io` using the credential with the reigstry name `https://index.docker.io/v1/`, which is really not a valid name (but it uses).

2022-09-10 09:42 UTC, shizhMSFT requested changes
Please update this PR as discussed to use the credentials of `https://index.docker.io/v1/` for `docker.io` when connecting `registry-1.docker.io` as `docker.io`. Meanwhile, please well document the docker behavior in the corresponding comment block.

2022-09-13 07:34 UTC, qweeah commented on cmd/oras/internal/option/remote.go
> +func (opts *Remote) authClient(host string, debug bool) (client *auth.Client, err error) {
Why we need this new argument? It's not used anywhere.

2022-09-13 08:16 UTC, qweeah requested changes
Can you add a unit test case for this host name replacement?

2022-09-13 08:25 UTC, shizhMSFT commented on cmd/oras/login.go
> +	if opts.Hostname == "docker.io" {
```suggestion
	if hostname  == "docker.io" {
```

2022-09-13 08:33 UTC, shizhMSFT approved these changes
LGTM

2022-09-13 08:36 UTC, shizhMSFT approved these changes
LGTM

2022-09-13 08:37 UTC, merged