fix: update argument description for platform
oras-project/oras pull request #606
Opened 2022-09-22 08:39 UTC by qweeah

#Resolves #598

Signed-off-by: Billy Zha <jinzha1@microsoft.com>

2022-09-22 08:56 UTC, FeynmanZhou commented on cmd/oras/internal/option/platform.go
> +	fs.StringVarP(&opts.Platform, "platform", "", "", "only fetch a specific platform if target is multi-platform capable, in the form of os[/arch][/variant][:os_version])")
My suggestion: `only fetch a manifest with specifying a specific platform if the target is multi-platform capable, in the form of os[/arch][/variant][:os_version])"`

2022-09-22 09:27 UTC, shizhMSFT requested changes

2022-09-22 09:27 UTC, shizhMSFT commented on cmd/oras/internal/option/platform.go
> +	fs.StringVarP(&opts.Platform, "platform", "", "", "only fetch a specific platform if target is multi-platform capable, in the form of os[/arch][/variant][:os_version])")
If target is a manifest list, the specified platform is selected.
If target is a manifest, the platform is ensured to match the specified platform.

```suggestion
	fs.StringVarP(&opts.Platform, "platform", "", "", "ensure fetching a manifest of a platform in the form of os[/arch][/variant][:os_version])")
```

2022-09-23 05:23 UTC, shizhMSFT approved these changes
LGTM

2022-09-23 05:44 UTC, lizMSFT approved these changes
LGTM

2022-09-23 07:37 UTC, shizhMSFT approved these changes
LGTM

2022-09-23 07:39 UTC, merged