refine CLI help doc
oras-project/oras pull request #619
Opened 2022-09-26 04:36 UTC by FeynmanZhou

Signed-off-by: Feynman Zhou <feynmanzhou@microsoft.com>

2022-09-26 11:30 UTC, qweeah commented on cmd/oras/attach.go
> +Example - Attach a file and export the pushed manifest to a specified path
```suggestion
Example - Attach file 'hi.txt' and export the pushed manifest to 'manifest.json'
```

2022-09-26 11:36 UTC, qweeah commented on cmd/oras/blob/fetch.go
> +	cmd.Flags().StringVarP(&opts.outputPath, "output", "o", "", "write it to standard output")
```suggestion
	cmd.Flags().StringVarP(&opts.outputPath, "output", "o", "", "output file `path`, use - for stdout")
```

2022-09-26 11:38 UTC, qweeah commented on cmd/oras/login.go
> +Example - Log in with username and password from user input:
```suggestion
Example - Log in with username and password from command line input:
```

2022-09-26 11:42 UTC, qweeah commented on cmd/oras/login.go
> +Example - Log in to an insecure registry from user input:
```suggestion
Example - Log in with username and password in an interactive terminal and no TLS check:
```

2022-09-26 11:46 UTC, qweeah commented on cmd/oras/manifest/fetch.go
> +	cmd.Flags().StringVarP(&opts.outputPath, "output", "o", "", "write it to standard output")
```suggestion
	cmd.Flags().StringVarP(&opts.outputPath, "output", "o", "", "file `path` to write the fetched manifest to, use - for stdout")
```

2022-09-26 11:48 UTC, qweeah commented on cmd/oras/manifest/fetch_config.go
> +	cmd.Flags().StringVarP(&opts.outputPath, "output", "o", "", "write it to standard output")
```suggestion
	cmd.Flags().StringVarP(&opts.outputPath, "output", "o", "", "file `path` to write the fetched config to, use - for stdout")
```

2022-09-26 11:53 UTC, qweeah commented on cmd/oras/tag/tag.go
> +Example - Tag the manifest 'v1.0.1' in 'localhost:5000/hello' to 'v1.0.2', 'latest' with concurrency level tuned:
```suggestion
Example - Tag the manifest 'v1.0.1' in 'localhost:5000/hello' to 'v1.0.1', 'v1.0.2', 'latest' with concurrency level tuned:
```

2022-09-26 11:54 UTC, qweeah requested changes
Thanks a lot for revising the docs!

2022-09-27 00:55 UTC, qweeah commented
@FeynmanZhou Can you rebase the PR to the latest main branch?

2022-09-27 00:57 UTC, qweeah commented on cmd/oras/tag/tag.go
> +Example - Tag the manifest 'v1.0.1' in 'localhost:5000/hello' to 'v1.0.1', 'v1.0.2', 'latest' with concurrency level tuned:
Sorry just realize that I made a mistake, can you help revert the change

```suggestion
Example - Tag the manifest 'v1.0.1' in 'localhost:5000/hello' to 'v1.0.2', 'latest' with concurrency level tuned:
```

2022-09-27 01:01 UTC, qweeah requested changes
Looks good to me.

2022-09-27 01:03 UTC, qweeah approved these changes
Looks good to me.

2022-09-27 01:38 UTC, shizhMSFT commented on cmd/oras/attach.go
> +
Remove empty line.

2022-09-27 01:38 UTC, shizhMSFT commented on cmd/oras/internal/option/remote.go
> +		fs.StringArrayVarP(&opts.Configs, "registry-config", "", nil, "path of the authentication file")
nit:
```suggestion
		fs.StringArrayVarP(&opts.Configs, "registry-config", "", nil, "`path` of the authentication file")
```

2022-09-27 01:38 UTC, shizhMSFT commented on cmd/oras/login.go
> +Example - Log in with username and password from user input:
nit:
```suggestion
Example - Log in with username and password from command line arguments:
```

2022-09-27 01:38 UTC, shizhMSFT commented on cmd/oras/login.go
> +Example - Log in with identity token from user input:
```suggestion
Example - Log in with identity token from command line arguments:
```

2022-09-27 01:41 UTC, FeynmanZhou commented on cmd/oras/login.go
> +Example - Log in with username and password from user input:
user input => command line flags

2022-09-27 01:42 UTC, FeynmanZhou commented on cmd/oras/login.go
> +Example - Log in with identity token from user input:
Same as above

2022-09-27 02:03 UTC, shizhMSFT approved these changes
LGTM

2022-09-27 02:05 UTC, merged