ci: run build against patch PR
oras-project/oras pull request #641
Opened 2022-10-11 07:50 UTC by qweeah

Resolves #640 

Signed-off-by: Billy Zha <jinzha1@microsoft.com>

2022-10-12 06:55 UTC, shizhMSFT requested changes
How about others? like CodeQL and license checker?

2022-10-12 07:08 UTC, qweeah commented
> How about others? like CodeQL and license checker?

Good point, updated.

2022-10-12 09:43 UTC, shizhMSFT commented on .github/workflows/license-checker.yml
>      branches: main
How about `push`?

2022-10-12 12:07 UTC, qweeah commented on .github/workflows/license-checker.yml
>      branches: main
You are right! Added.

2022-10-13 05:43 UTC, shizhMSFT approved these changes
LGTM

2022-10-13 05:44 UTC, merged